### ISSUE TITLE
Mixin TimeStamp

### ISSUE THREAD

**Issue by morexlt** [IngSisFAI/volunt-api#1]
[https://github.com/IngSisFAI/volunt-api/commit/4d7c1d23c924e0f8e9b4d6b33305eb1e3e94a162](Commit)
Error: Model "DonnerReview" uses unknown mixin: TimeStamp

```
/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-datasource-juggler/lib/mixins.js:50
      throw new Error(errMsg);
      ^

Error: Model "DonnerReview" uses unknown mixin: TimeStamp
    at MixinProvider.applyMixin (/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-datasource-juggler/lib/mixins.js:50:13)
    at ModelBuilder.defineClass [as define] (/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-datasource-juggler/lib/model-builder.js:657:27)
    at Function.ModelClass.extend (/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-datasource-juggler/lib/model-builder.js:455:33)
    at Registry.createModel (/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback/lib/registry.js:122:25)
    at /home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-boot/lib/executor.js:245:24
    at Array.forEach (native)
    at defineModels (/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-boot/lib/executor.js:229:23)
    at setupModels (/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-boot/lib/executor.js:197:3)
    at execute (/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-boot/lib/executor.js:40:3)
    at bootLoopBackApp (/home/morexlt/Documentos/work/voluntariado2017-server/node_modules/loopback-boot/index.js:154:3)
    at Object.<anonymous> (/home/morexlt/Documentos/work/voluntariado2017-server/server/server.js:23:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by morexlt** [comment]
Fixed, Faltaba instalar dependency.
**loopback-ds-timestamp-mixin**
[https://github.com/IngSisFAI/volunt-api/commit/98a54b4cd8eeb838ae1ae1904c23e910feb2e810](url)

**Comment by webocs** [comment]
Me olvide el save y debo tener node 6 en la notebook.
